<?php

namespace TA\CurriculumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseToCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseToCategoryRepository extends EntityRepository
{
}
